
package com.donlim.pm.webservice.eip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "CheckSearch", targetNamespace = "urn:DefaultNamespace")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CheckSearch {


    /**
     *
     * @param oappbody
     * @param osvchdr
     * @param oapphdr
     * @return
     *     returns com.donlim.pm.webservice.eip.SVCBODYS
     */
    @WebMethod(operationName = "SYNCHECKSEARCH")
    @WebResult(name = "SYNCHECKSEARCHReturn", targetNamespace = "")
    @RequestWrapper(localName = "SYNCHECKSEARCH", targetNamespace = "urn:DefaultNamespace", className = "com.donlim.pm.webservice.eip.SYNCHECKSEARCH")
    @ResponseWrapper(localName = "SYNCHECKSEARCHResponse", targetNamespace = "urn:DefaultNamespace", className = "com.donlim.pm.webservice.eip.SYNCHECKSEARCHResponse")
    public SVCBODYS synchecksearch(
        @WebParam(name = "OSVCHDR", targetNamespace = "")
                SVCHDR osvchdr,
        @WebParam(name = "OAPPHDR", targetNamespace = "")
                APPHDR oapphdr,
        @WebParam(name = "OAPPBODY", targetNamespace = "")
                APPBODY oappbody);

}
