<html>
<head>
</head>
<body text="#000000">
<ul>
<li>Domino<a href="http://bsappserver.donlim.com:80/bs/AssetManagerSystem.nsf/WSCHECKSEARCH?WSDL"><i>(wsdl)</i></a></li>
<ul>
<li>SYNCHECKSEARCH
</ul>
</ul>
</body>
</html>
