
package com.donlim.pm.webservice.ipp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "DONLIM_IMOS_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_IMOS_QUERYSYNC/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DONLIMIMOSQUERYSYNC {


    /**
     *
     * @param svcHdr
     * @return
     *     returns com.donlim.pm.webservice.ipp.SvcHdrsType
     */
    @WebMethod(operationName = "DONLIM_IMOS_QUERYSYNC", action = "http://www.example.org/DONLIM_IMOS_QUERYSYNC/DONLIM_IMOS_QUERYSYNC")
    @WebResult(name = "SvcHdrs", targetNamespace = "")
    @RequestWrapper(localName = "DONLIM_IMOS_QUERYSYNC", targetNamespace = "http://www.example.org/DONLIM_IMOS_QUERYSYNC/", className = "com.donlim.pm.webservice.ipp.DONLIMIMOSQUERYSYNC_Type")
    @ResponseWrapper(localName = "DONLIM_IMOS_QUERYSYNCResponse", targetNamespace = "http://www.example.org/DONLIM_IMOS_QUERYSYNC/", className = "com.donlim.pm.webservice.ipp.DONLIMIMOSQUERYSYNCResponse")
    public SvcHdrsType donlimIMOSQUERYSYNC(
        @WebParam(name = "SvcHdr", targetNamespace = "")
                SvcHdrType svcHdr);

}
